[project]
name = "simple-chainlit-chatbot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "chainlit>=2.9.0",
    "langchain>=1.0.5",
    "langchain-google-genai>=3.0.3",
]
